apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app01-deployment
  labels:
    app: sample-app01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app01
  template:
    metadata:
      labels:
        app: sample-app01
    spec:
      containers:
      - name: sample-app01
        image: vinish86/springboot:42
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: sample-app01-service
spec:
  selector:
    app: sample-app01
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: sample-app01-ingress
spec:
  rules:
  - host: sample-app01.ronsonk8s.com
    http:
      paths:
      - backend:
          serviceName: sample-app01-service
          servicePort: 8080
        path: /

