apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: dev-role
  namespace: development
rules:
- apiGroups: ["*"]
  resources: ["deployments","statefulsets","services","pods","configmaps","secrets","replicasets","ingresses","endpoints","cronjobs","jobs","persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "update", "patch", "create"]
