kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: interns-binding
  namespace: testing
subjects:
- kind: Group
  name: interns
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: interns
  apiGroup: rbac.authorization.k8s.io
